# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef9febbba7713247d51b83feb7de518f9ed20b6ace1b1d806bfd5cda0ef50153ccf655cc1312ebca3787cfa072de08a89e9aff7037a70063f535cb24eb64a769

test:
  secret_key_base: f952ec718f5a6711c56b4be17f26354f40d2cf3a50505ff99038ec01cbb8ab60637327dccda9e89d3fcd75c4399c898684a9f721452bf7a0926aa473977a6766

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
